name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks (Shard #${{ matrix.shard }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v5
      - name: Install required-version defined in uv.toml
        uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12.8
      - name: Run the benchmarks
        if: ${{ !github.event.repository.fork }}
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: uv run pytest tests/benchmarks/ --codspeed --test-group=${{ matrix.shard }} --test-group-count=4
